# Generated by Django 3.1 on 2020-09-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('correct', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
